package main

import (
	"time"
	"fmt"
	wr "github.com/mroth/weightedrand"
)

func main() {
	c := wr.NewChooser(
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍆", Weight: 0},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
		wr.Choice{Item: "🍋", Weight: 1},
		wr.Choice{Item: "🍊", Weight: 1},
		wr.Choice{Item: "🍉", Weight: 3},
		wr.Choice{Item: "🥑", Weight: 5},
	)
	fmt.Println(c.Pick().(string))

	st := time.Now().Nanosecond()
	list:=c.PickN(20)
	et := time.Now().Nanosecond()
	fmt.Println(et-st, list)
}
